# Generated by Django 4.1.5 on 2023-01-16 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurer',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumption_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('measurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.measurer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(check=models.Q(('consumption_kwh__gte', 0.0)), name='min_consumption_kwh'),
        ),
    ]
